import contestantsJson from '@/data/normalized/contestants.json'
import type { Contestant } from './types'

// The JSON file is generated by our typed ingestion pipeline. TypeScript infers a
// union from optional JSON keys, so cross the serialization boundary explicitly.
export const contestants = contestantsJson as unknown as Contestant[]

function participantCount(item: Contestant) {
  return item.members?.length || 1
}

export function getStats(items = contestants) {
  const withAge = items.filter((c) => typeof c.age === 'number')
  const winners = items.filter((c) => c.winner)
  const withScore = items.filter((c) => typeof c.score === 'number')

  return {
    entries: items.length,
    participants: items.reduce((sum, item) => sum + participantCount(item), 0),
    // Backward-compatible alias while the codebase migrates from the original
    // person-only model to individual/couple competition entries.
    contestants: items.length,
    seasons: new Set(items.map((c) => c.season)).size,
    winners: winners.length,
    averageAge: withAge.length
      ? Math.round(withAge.reduce((sum, c) => sum + (c.age ?? 0), 0) / withAge.length)
      : null,
    averageWinnerAge: winners.filter((c) => c.age).length
      ? Math.round(
          winners.reduce((sum, c) => sum + (c.age ?? 0), 0) /
            winners.filter((c) => c.age).length,
        )
      : null,
    topScore: withScore.length ? Math.max(...withScore.map((c) => c.score ?? 0)) : null,
    dishes: items.reduce((sum, c) => sum + c.dishes.length, 0),
    sources: new Set(items.flatMap((c) => c.sources.map((source) => `${source.kind}:${source.url}`))).size,
  }
}
